import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Search, Download, Link2, Check } from "lucide-react";
import { AgentBadge } from "@/components/EsaLogo";
import { MOCK_REPORTS } from "@/lib/mockData";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports — ESA" }] }),
  component: Reports,
});

const MOCK_CONTENT: Record<string, string> = {
  r1: "Q3 REVENUE PERFORMANCE & Q4 FORECAST\n\nExecutive Summary\nQ3 revenue: $61.4M (+14% QoQ). September exceeded target by 5.8%.\n\nQ4 Forecast: $68–72M base case.\n\nKey Drivers:\n- Enterprise upsells: +$4.2M\n- New logo ARR: +$3.1M\n- Expansion revenue: +$2.8M",
  r2: "COMPETITOR MATRIX — CRM VENDORS\n\nVendor,Price,NPS,SSO\nAcme (You),$49,62,Yes\nSalesforce,$165,41,Yes\nHubSpot,$90,54,Yes\nZoho,$35,48,No\nPipedrive,$29,51,No",
  r3: "CHURN COHORT ANALYSIS — H1 2026\n\nMonth,Churn Rate\nJan,3.2%\nFeb,2.8%\nMar,2.5%\nApr,2.9%\nMay,2.1%\n\nKey Finding: Churn reduced 34% YTD. May reached all-time low.",
  r4: "PRICING BENCHMARK — APAC SAAS\n\nMedian APAC SaaS pricing: $65/seat/month\nAcme current: $49/seat/month\nGap: 25% below market\nRecommendation: 10-15% price increase on Growth tier.",
  r5: "CUSTOMER NPS TRENDS\n\nMonth,NPS,Responses\nJan,41,124\nFeb,47,138\nMar,54,156\nApr,58,162\nMay,62,171",
};

function mockDownload(title: string, id: string, type: string) {
  const content = MOCK_CONTENT[id] ?? `${title}\n\nGenerated by ESA on ${new Date().toLocaleDateString()}`;
  const ext = type === "CSV" ? "csv" : type === "PPT" ? "txt" : "txt";
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${title.replace(/\s+/g, "_")}.${ext}`; a.click();
  URL.revokeObjectURL(url);
}

function CopyLink({ id }: { id: string }) {
  const [copied, setCopied] = useState(false);
  function copy() {
    navigator.clipboard.writeText(`${window.location.origin}/reports?id=${id}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }
  return (
    <button onClick={copy} className="text-text-tertiary hover:text-primary transition-colors" title="Copy link">
      {copied ? <Check className="w-4 h-4 text-success" /> : <Link2 className="w-4 h-4" />}
    </button>
  );
}

function Reports() {
  const [query, setQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState("All types");

  const filtered = MOCK_REPORTS.filter((r) => {
    const matchQ = r.title.toLowerCase().includes(query.toLowerCase());
    const matchT = typeFilter === "All types" || r.type === typeFilter;
    return matchQ && matchT;
  });

  return (
    <DashboardLayout title="Reports">
      <div className="p-6 max-w-6xl mx-auto space-y-5">
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative flex-1 min-w-[240px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-tertiary" />
            <input value={query} onChange={(e) => setQuery(e.target.value)}
                   placeholder="Search reports..."
                   className="w-full h-10 pl-10 pr-3 rounded-md bg-surface border border-border-strong text-[14px] focus:outline-none focus:border-primary transition-colors" />
          </div>
          <select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}
                  className="h-10 px-3 rounded-md bg-surface border border-border-strong text-[13px] focus:outline-none focus:border-primary">
            <option>All types</option><option>PDF</option><option>PPT</option><option>CSV</option>
          </select>
        </div>

        <div className="bg-surface border border-border rounded-xl overflow-hidden shadow-l1">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="bg-secondary text-[12px] text-text-secondary text-left">
                {["Title", "Generated", "Type", "Agents", "Download", "Share"].map((h) => (
                  <th key={h} className="px-4 py-3 font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((r) => (
                <tr key={r.id} className="border-t border-border hover:bg-secondary/50 transition-colors">
                  <td className="px-4 py-3 text-text-primary font-medium">{r.title}</td>
                  <td className="px-4 py-3 text-text-tertiary">{r.time}</td>
                  <td className="px-4 py-3">
                    <span className={cn("text-[11px] px-2 py-0.5 rounded-full font-semibold",
                      r.type === "PDF" && "bg-danger/10 text-danger",
                      r.type === "PPT" && "bg-warning/10 text-warning",
                      r.type === "CSV" && "bg-success/10 text-success",
                    )}>{r.type}</span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex flex-wrap gap-1">{r.agents.map((a) => <AgentBadge key={a} agent={a} />)}</div>
                  </td>
                  <td className="px-4 py-3">
                    <button onClick={() => mockDownload(r.title, r.id, r.type)}
                            className="flex items-center gap-1 text-primary text-[12px] hover:underline transition-colors">
                      <Download className="w-3.5 h-3.5" /> {r.type}
                    </button>
                  </td>
                  <td className="px-4 py-3">
                    <CopyLink id={r.id} />
                  </td>
                </tr>
              ))}
              {filtered.length === 0 && (
                <tr><td colSpan={6} className="px-4 py-8 text-center text-text-tertiary">No reports found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </DashboardLayout>
  );
}
